---
- name: Ensure ufw is installed
  ansible.builtin.apt:
    name: ufw
    state: present

- name: Ensure ufw is running and enabled
  ansible.builtin.ufw:
    state: enabled

- name: Check if port {{ firewall_http_port }} is already open
  ansible.builtin.ufw:
    rule: allow
    port: "{{ firewall_http_port }}"
    proto: tcp
  check_mode: yes
  register: firewall_check
  changed_when: false

- name: Open port {{ firewall_http_port }} (HTTP) in ufw if not already open
  ansible.builtin.ufw:
    rule: allow
    port: "{{ firewall_http_port }}"
    proto: tcp
  when: firewall_check.changed

- name: Check if port {{ firewall_http_port }} is listening
  shell: netstat -tuln | grep :{{ firewall_http_port }}
  register: port_check
  changed_when: false
  failed_when: false

- name: Display port {{ firewall_http_port }} status
  debug:
    msg: "Port {{ firewall_http_port }} is {{ 'listening' if port_check.rc == 0 else 'not listening' }}"
