---
- name: Check if PostgreSQL container is running
  docker_container_info:
    name: postgres
  register: postgres_container_info

- name: Check if PostgreSQL data directory exists
  stat:
    path: "{{ postgres_data_dir }}"
  register: postgres_data_dir_stat

- name: Create PostgreSQL data directory
  file:
    path: "{{ postgres_data_dir }}"
    state: directory
    mode: '0755'
  when: not postgres_data_dir_stat.stat.exists

- name: Run PostgreSQL Docker container
  docker_container:
    name: postgres
    image: "postgres:{{ postgres_version }}"
    state: started
    restart_policy: always
    ports:
      - "{{ postgres_port }}:5432"
    env:
      POSTGRES_PASSWORD: "{{ postgres_password }}"
    volumes:
      - "{{ postgres_data_dir }}:/var/lib/postgresql/data"
  when: postgres_container_info.exists == false
