---
- name: Ensure the deploy user exists
  ansible.builtin.user:
    name: deploy_user
    state: present
    shell: /bin/bash

- name: Create .ssh directory
  ansible.builtin.file:
    path: /home/deploy_user/.ssh
    state: directory
    owner: deploy_user
    group: deploy_user
    mode: '0700'

- name: Add authorized keys
  ansible.builtin.authorized_key:
    user: deploy_user
    key: "{{ lookup('file', item) }}"
  with_items: "{{ ssh_keys }}"

- name: Add deploy_user to sudoers
  ansible.builtin.lineinfile:
    path: /etc/sudoers
    state: present
    regexp: '^deploy_user'
    line: 'deploy_user ALL=(ALL) NOPASSWD:ALL'

- name: Create .ansible directory for deploy_user
  ansible.builtin.file:
    path: /home/deploy_user/.ansible
    state: directory
    owner: deploy_user
    group: deploy_user
    mode: '0755'

- name: Create tmp directory inside .ansible
  ansible.builtin.file:
    path: /home/deploy_user/.ansible/tmp
    state: directory
    owner: deploy_user
    group: deploy_user
    mode: '0775'
