---
- name: Check if DragonflyDB container is running
  docker_container_info:
    name: dragonflydb
  register: dragonflydb_container_info

- name: Run DragonflyDB Docker container
  docker_container:
    name: dragonflydb
    image: docker.dragonflydb.io/dragonflydb/dragonfly
    state: started
    restart_policy: always
    ports:
      - "{{ dragonfly_port }}:6379"
    command: dragonfly --bind 0.0.0.0 --port {{ dragonfly_port }}
  when: dragonflydb_container_info.exists == false
