---
- name: Check if template7pg directory exists
  stat:
    path: "{{ template7pg_data_dir }}"
  register: template7pg_dir

- name: Create directory on host for template7pg files
  file:
    path: "{{ template7pg_data_dir }}"
    state: directory
    mode: '0755'
    owner: '1000'
    group: '1000'
  when: not template7pg_dir.stat.exists

- name: Copy files from image to host
  command: >
    docker run --rm -v {{ template7pg_data_dir }}:/backup nkhphuc/template7pg:latest
    bash -c "cp -r /rails/. /backup"
  changed_when: false
  when: not template7pg_dir.stat.exists

- name: Set permissions on copied files
  file:
    path: "{{ template7pg_data_dir }}"
    owner: '1000'
    group: '1000'
    mode: '0755'
    recurse: yes
  when: not template7pg_dir.stat.exists

- name: Run template7pg Docker container
  docker_container:
    name: template7pg
    image: nkhphuc/template7pg:latest
    state: started
    restart_policy: always
    ports:
      - "{{ template7pg_port }}:3000"
    env:
      RAILS_MASTER_KEY: "{{ rails_master_key }}"
      RAILS_ENV: "{{ rails_env }}"
      REDIS_URL_DEVELOPMENT: "redis://{{ ansible_private_ip }}:{{ dragonfly_port }}"
      DEV_DATABASE_HOST: "{{ ansible_private_ip }}"
      DEV_DATABASE_PORT: "{{ postgres_port }}"
    volumes:
      - "{{ template7pg_data_dir }}:/rails"
