---
- name: Check if app_network exists
  command: docker network inspect {{ docker_network_name }}
  register: network_check
  ignore_errors: yes
  changed_when: false

- name: Create Docker network if it doesn't exist
  docker_network:
    name: "{{ docker_network_name }}"
    state: present
  when: network_check.rc != 0

- name: Verify network status
  command: docker network inspect {{ docker_network_name }}
  register: network_inspect

- name: Display network info
  debug:
    var: network_inspect.stdout_lines
