---
- name: Create Nginx configuration file
  template:
    src: "nginx.conf.{{ rails_env | truncate(3,true,'') }}.j2"
    dest: /home/{{ ansible_user }}/nginx.conf
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0644'

- name: Run Nginx Docker container
  docker_container:
    name: nginx
    image: nginx:latest
    state: started
    restart_policy: always
    ports:
      - "{{ nginx_port }}:80"
    volumes:
      - /home/{{ ansible_user }}/nginx.conf:/etc/nginx/nginx.conf:ro
