---
- name: Create a deploy user
  hosts: dev_web_servers
  become: yes
  tasks:
    - name: Ensure the deploy user exists
      ansible.builtin.user:
        name: deploy_user
        state: present
        shell: /bin/bash

    - name: Create .ssh directory
      ansible.builtin.file:
        path: /home/deploy_user/.ssh
        state: directory
        owner: deploy_user
        group: deploy_user
        mode: '0700'

    - name: Copy authorized keys
      ansible.builtin.copy:
        src: /Users/hopee/.ssh/hopee_mac_github_1.pub
        dest: /home/deploy_user/.ssh/authorized_keys
        owner: deploy_user
        group: deploy_user
        mode: '0600'

    - name: Add deploy_user to sudoers
      ansible.builtin.lineinfile:
        path: /etc/sudoers
        state: present
        regexp: '^deploy_user'
        line: 'deploy_user ALL=(ALL) NOPASSWD:ALL'
