---
- name: Playbook to deploy and run nkhphuc/template7pg using docker in dev environment
  hosts: aws_dev_web_servers
  become: yes
  remote_user: "{{ deploy_user }}"
  gather_facts: yes
  vars:
    rails_env: "development"
    # ansible_user: "{{ ansible_ssh_user }}"
    ansible_user: "{{ deploy_user }}"
  pre_tasks:
    - name: Include encrypted secrets
      include_vars:
        file: secrets.yml
    - name: Set variables from secrets
      set_fact:
        rails_master_key: "{{ vault_rails_master_key }}"
        github_repo_url: "{{ vault_github_repo_url }}"
  roles:
    - role: info
    - role: docker
      vars:
        docker_user: "{{ ansible_user }}"
    - role: docker_postgres
      vars:
        postgres_password: "{{ vault_postgres_password | default('password') }}"
    - role: docker_dragonflydb
    # - role: docker_nginx
    #   vars:
    #     nginx_port: "80"
    #     app_server_ip: "{{ ansible_private_ip }}"

    # not tested yet
    - role: docker_caddy
      vars:
        caddy_port: "80"
        app_server_ip: "{{ ansible_private_ip }}"
    - role: docker_ollama
      vars:
        ollama_data_dir: "/home/{{ ansible_user }}/ollama_data"

    # The following role is commented out because it is not recommended for use. It has several downsides: when used with Ansible, it will bypass docker-entrypoint. It uses a 3rd party service (Docker Hub) that requires additional setup and fees. Also, it is not versatile when it comes to deploying different versions or environments of the app.
    # - role: docker_template7pg
    #   vars:
    #     template7pg_data_dir: "/home/{{ ansible_user }}/template7pg_data"
    #     template7pg_port: "3000"

    - role: template7pg_compose
      vars:
        ansible_user_uid: "1000"
        ansible_user_gid: "1000"
