---
- name: Playbook to deploy and run nkhphuc/template7pg using docker in dev environment
  hosts: aws_dev_web_servers
  become: yes
  remote_user: "{{ deploy_user }}"
  gather_facts: yes
  vars:
    rails_env: "development"
    ansible_user: "{{ deploy_user }}"
    docker_user: "{{ deploy_user }}"
    app_public_ip: "{{ ansible_public_ip }}"
    app_private_ip: "{{ ansible_private_ip }}"
    ansible_user_uid: "1000"
    ansible_user_gid: "1000"
    # dev_database_host: "{{ ansible_private_ip }}"
    # redis_url: "redis://{{ ansible_private_ip }}:6379/1"
  pre_tasks:
    - name: Include encrypted secrets
      include_vars:
        file: secrets.yml
    - name: Set variables from secrets
      set_fact:
        rails_master_key: "{{ vault_rails_master_key }}"
        github_repo_url: "{{ vault_github_repo_url }}"
        postgres_user: "{{ vault_postgres_dev_user | default('postgres') }}"
        postgres_password: "{{ vault_postgres_dev_password | default('password') }}"
  roles:
    - role: info
    - role: docker
    - role: docker_postgres
    - role: docker_dragonflydb
    # - role: docker_nginx
    - role: docker_caddy
    - role: template7pg_compose
